In [1]:
import numpy as np

### reshape
- reshape: Array의 shape을 변경함, element의 개수는 동일
- -1: size를 기반으로 row 개수 선정

In [2]:
test_matrix = [[1,2,3,4],[1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [3]:
np.array(test_matrix).reshape(4,2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

In [4]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [5]:
# 원래 데이터인 test_matrix는 변경되지 않음
test_matrix

[[1, 2, 3, 4], [1, 2, 5, 8]]

In [6]:
np.array(test_matrix).reshape(8)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [7]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [8]:
np.array(test_matrix).reshape(2,-1)

array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

In [9]:
np.array(test_matrix).reshape(1,-1,2)

array([[[1, 2],
        [3, 4],
        [1, 2],
        [5, 8]]])

### flat or flatten()
- flatten : 다차원 array를 1차원 array로 변환

In [10]:
test_matrix = [[[1,2,3,4],[1,2,5,8]],[[1,2,3,4],[1,2,5,8]]]
np.array(test_matrix)

array([[[1, 2, 3, 4],
        [1, 2, 5, 8]],

       [[1, 2, 3, 4],
        [1, 2, 5, 8]]])

In [12]:
test_matrix = np.array(test_matrix)
test_matrix.shape

(2, 2, 4)

In [14]:
test_matrix.flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

In [15]:
test_matrix.flatten().size

16

In [16]:
test_matrix.flatten().shape

(16,)