In [4]:
import numpy as np

### indexing
- list와 달리 이차원 배열에서 [0,0]표기법을 제공함
- matrix일 경우, 앞은 row 뒤는 column을 의미함

In [5]:
test_example = np.array([[1,2,3],[4.5,5,6]], int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
test_example[0][2]

3

In [7]:
test_example[0,2]

3

In [8]:
test_example[0,0] = 10
test_example

array([[10,  2,  3],
       [ 4,  5,  6]])

In [9]:
test_example[1,2] = 5
test_example[1,2]

5

In [10]:
test_example

array([[10,  2,  3],
       [ 4,  5,  5]])

### slicing
- list와 달리 행과 열 부분을 나눠서 slicing이 가능함
- matrix의 부분 집합을 추출할 때 유용함

In [11]:
test_example = np.array([[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]], int)
test_example

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [12]:
test_example[:, 2:]  # 전체 행의 2열 이상

array([[5, 8],
       [5, 8],
       [5, 8],
       [5, 8]])

In [13]:
test_example  # 원본 데이터 변경 없음

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [14]:
test_example[:, 1:3]  # 전체 행의 1~2열

array([[2, 5],
       [2, 5],
       [2, 5],
       [2, 5]])

In [15]:
test_example[1:2, :2]  # 1행의 2열 이상

array([[1, 2]])

In [16]:
test_example = np.array([[1,2,3,4,5],[6,7,8,9,10]], int)
test_example

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
test_example[1]  # 1행의 모든 열

array([ 6,  7,  8,  9, 10])

In [18]:
test_example[1:2]  # 1행의 모든 열, 2차원 array

array([[ 6,  7,  8,  9, 10]])

In [19]:
a = np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [21]:
a[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])