In [1]:
import numpy as np

### arange
- array의 범위를 지정하여, 값의 list를 생성하는 명령어
- arange(start,end,step)

In [2]:
list(range(0,10,3))

[0, 3, 6, 9]

In [3]:
type(list(range(30)))

list

In [5]:
# range: List의 range와 같은 효과,
# integer로 0부터 20까지 배열 추출
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [7]:
# floating point도 표시가능함
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [8]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### ones, zeros & empty
- zeros: 0으로 가득찬 ndarray 생성
    - np.zeros(shape,dtype,order)
- ones: 1로 가득찬 ndarray 생성
    - np.ones(shape, dtype,order)
- empty: shape만 주어지고 비어있는 ndarray 생성 (memory initialization이 되지 않음)
- something_like: 기존 ndarray의 shape 크기 만큼 1,0 또는 emptyarray를 반환

In [9]:
# zero vector 생성
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [10]:
# 2 by 5 - zero matrix 생성
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [13]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.empty(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [16]:
np.empty((3,5))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 2.56761491e-312]])

In [17]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [18]:
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

### identity
- 단위 행렬(identity matrix)를 생성함

In [19]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [20]:
np.identity(n=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### eye
- 대각선이 1인 행렬, k값의 시작 index의 변경이 가능

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [24]:
np.eye(3,5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### diag
- 대각 행렬의 값을 추출함

In [26]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [28]:
np.diag(matrix, k=1)  # k는 start index

array([1, 5])

### numpy.random
- 데이터 분포에 따른 sampling으로 array를 생성

In [29]:
# 균등 분포
np.random.uniform(0,1,10).reshape(2,5)

array([[0.56168619, 0.7889927 , 0.19526191, 0.87212823, 0.89034203],
       [0.0330818 , 0.73786851, 0.51611359, 0.25459029, 0.89505477]])

In [30]:
# 정규 분포
np.random.normal(0,1,10).reshape(2,5)

array([[-1.90751223e+00, -1.16927963e-03, -3.68804561e-01,
         8.96480069e-01,  2.28348772e+00],
       [-1.18387803e+00,  4.67777476e-01,  1.11222487e-01,
        -2.05008949e+00,  5.18418627e-01]])