In [1]:
import numpy as np

### Array operations
- Element-wise operations: Array간 shape이 같을 때 일어나는 연산

In [5]:
test_a = np.array([[1,2,3],[4,5,6]], float)
test_a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [6]:
test_a + test_a  # Matrix + Matrix 연산

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [7]:
test_a - test_a  # Matrix - Matrix 연산

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
test_a * test_a  # Matrix내 element들 간 같은 위치에 있는 값들끼리 연산

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [9]:
matrix_a = np.arange(1,13).reshape(3,4)
matrix_a - matrix_a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Dot product
- Matrix의 기본 연산, dot함수 사용

In [10]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)
test_a, test_b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]]))

In [11]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

### transpose
- transpose 또는 T attribute 사용

In [12]:
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
test_a.T.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

### broadcasting
- shape이 다른 배열 간 연산을 지원하는 기능

In [16]:
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3

In [17]:
test_matrix + scalar  # Matrix-Scalar 덧셈

array([[4., 5., 6.],
       [7., 8., 9.]])

In [18]:
test_matrix - scalar  # Matrix-Scalar 뺄셈

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [20]:
test_matrix * 5  # Matrix-Scalar 곱셈

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [21]:
test_matrix / 5  # Matrix-Scalar 나눗셈

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [22]:
test_matrix // 0.2  # Matrix-Scalar 몫

array([[ 4.,  9., 14.],
       [19., 24., 29.]])

In [23]:
test_matrix ** 2  # Matrix-Scalar 제곱

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [24]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10, 40, 10)
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

### numpy performance
- **timeit**: jupyter환경에서 코드의 퍼포먼스를 체크하는 함수 

In [26]:
def sclar_vector_product(scalar,vector):
    result = []
    for value in vector:
        result.append(scalar*value)
    return result

iternation_max = 100000000
vector = list(range(iternation_max))
scalar = 2

%timeit sclar_vector_product(scalar,vector)  #forloop을이용한성능
%timeit [scalar*value for value in range(iternation_max)]  #listcomprehension을이용한성능
%timeit np.arange(iternation_max)*scalar  #numpy를이용한성능

10.6 s ± 501 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
8.64 s ± 22.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
237 ms ± 7.14 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


- 일반적으로 속도는 아래 순
  for loop < list comprehension <numpy
- 100,000,000번의 loop이 돌 때,약 4배 이상의 성능 차이를 보임
- NumPy는 C로 구현되어 있어,성능을 확보하는 대신 파이썬의 가장 큰 특징인dynamic typing을 포기함
- 대용량 계산에서는 가장 흔히 사용됨
- Concatenate처럼 계산이 아닌,할당에서는 연산 속도의 이점이 없음