In [1]:
import numpy as np

### boolean index
- 특정 조건에 따른 값을 배열 형태로 추출
- Comparison operation함수들도 모두 사용 가능

In [2]:
test_array = np.array([1,4,0,2,3,8,9,7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [4]:
# 조건이 True인 index의 element만 추출
test_array[test_array > 3]

array([4., 8., 9., 7.])

In [5]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

### fancy index
- NumPy는 array를 index value로 사용해서 값 추출

In [6]:
a = np.array([2,4,6,8], float)
b = np.array([0,0,1,3,2,1], int)  # 반드시 integer로 선언

# braket index, b 배열의 값을 index로 하여 a의 값들을 추출함
a[b]

array([2., 2., 4., 8., 6., 4.])

In [7]:
# take 함수 : braket index와 같은 효과
a.take(b)

array([2., 2., 4., 8., 6., 4.])

In [8]:
a = np.array([[1,4],[9,16]], float)
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1], int)

# b를 row index, c를 column index로 변환하여 표시함
a[b,c]

array([ 1.,  4., 16., 16.,  4.])